version: '3'

services:
  ruby:
    build: .
    volumes:
      - .:/rails-template
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: 'no'
    links:
      - postgres
    command: bundle exec rails s -b 0.0.0.0
  postgres:
    image: postgres:12.6-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: 'no'

volumes:
  db:
    driver: local
