version: '3'

services:
  ruby:
    build: .
    volumes:
      - .:/rails-template:cached
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: 'no'
    links:
      - postgres
    command: |
      bash -c '
        yarn install &&
        yarn dev'
  postgres:
    image: postgres:11.9-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: 'no'

volumes:
  db:
    driver: local
